version: '3.8'
networks:
  docker-analytics-network:
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: analytics
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - docker-analytics-network
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ..:/var/www/html
#      - ./php/conf:/usr/local/etc/php-fpm.d
#      - /var/www/html/docker
    depends_on:
      - database
    networks:
      - docker-analytics-network
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '9080:80'
    volumes:
      - ..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
#      - /var/www/html/docker
    depends_on:
      - php
      - database
    networks:
      - docker-analytics-network